# Custom Language File for Launcher Customizer

[ejs.app]
title = "ФЛАУНЧЕР"

[ejs.landing]
mediaGitHubURL = "https://github.com/Envel-Experimental/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Envel-Experimental/HeliosLauncher"
supportLink = "https://github.com/Envel-Experimental/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Добро пожаловать в ФЛАУНЧЕР!"
welcomeDescription = "Далее мы создадим тебе аккаунт в Minecraft. Придумай игровое имя из больших и/или маленьких английских букв, можно использовать цифры и символ нижнего подчеркивания. От 4 до 16 символов."
welcomeDescCTA = 'На следующей странице нажми "Создать аккаунт" и введи игровое имя.'

[js.distro.verification]
title = "Предупреждение безопасности"
desc = "Цифровая подпись важного файла недействительна.<br><br>Это может означать, что файл был изменен хакером или поврежден.<br>Продолжение может быть небезопасным.<br>Мы не несем ответственности за возможные проблемы,<br>связанные с нажатием кнопки 'Продолжить'."
proceed = "Продолжить"
retry = "Повторить"
close = "Закрыть"
