[ejs.landing]
updateAvailableTooltip = "Update Available"
usernamePlaceholder = "Username"
usernameEditButton = "Edit"
settingsTooltip = "Settings"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Not&nbsp;Required"
newsButton = "Resources"
launchButton = "PLAY"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "Please wait.."
settingsButton = "SETTINGS"
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Checking for news.."
newsErrorFailedSpan = "Failed to load news"
newsErrorRetryButton = "Retry"
newsErrorNoneSpan = "No news"

[ejs.login]
loginCancelText = "Cancel"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Invalid value"
loginEmailPlaceholder = "USERNAME"
loginPasswordError = "* Required"
loginPasswordPlaceholder = "PASSWORD"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "forgot password?"
loginRememberMeText = "remember me?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Need an account?"
loginPasswordDisclaimer1 = "Username must be in English and may contain numbers and underscores. 4 to 16 characters."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Login Options"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Create Account"
cancelButton = "Cancel"

[ejs.overlay]
serverSelectHeader = "Select Course"
serverSelectConfirm = "Select"
serverSelectCancel = "Cancel"
accountSelectHeader = "Select Account"
accountSelectConfirm = "Select"
accountSelectCancel = "Cancel"

[ejs.settings]
navHeaderText = "Settings"
navAccount = "Account"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "About"
navUpdates = "Updates"
navDone = "Done"
tabAccountHeaderText = "Account Settings"
tabAccountHeaderDesc = "Add new accounts or manage existing ones."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Add Microsoft Account"
mojangAccount = "Regular Account"
addMojangAccount = "+ Add Account"
minecraftTabHeaderText = "Minecraft Settings"
minecraftTabHeaderDesc = "Parameters related to launching the game."
gameResolutionTitle = "Game Resolution"
launchFullscreenTitle = "Launch in fullscreen."
autoConnectTitle = "Automatically connect to the server on launch."
launchDetachedTitle = "Launch game detached from launcher."
launchDetachedDesc = "If the game is not detached, closing the launcher will also close the game."
tabModsHeaderText = "Mod Settings"
tabModsHeaderDesc = "Enable or disable mods."
switchServerButton = "Switch"
requiredMods = "Required Mods"
optionalMods = "Optional Mods"
dropinMods = "Drop-in Mods"
addMods = "Add Mods"
dropinRefreshNote = "(F5 to refresh)"
shaderpacks = "Shaders"
shaderpackDesc = "Enable or disable shaders. Note that shaders only work on powerful devices. Custom packs can be added here."
selectShaderpack = "Select Shader"
tabJavaHeaderText = "Java Settings"
tabJavaHeaderDesc = "Manage Java settings (advanced)."
memoryTitle = "Memory"
maxRAM = "Maximum RAM"
minRAM = "Minimum RAM"
memoryDesc = "The recommended minimum RAM is 3 GB. Setting the same values for minimum and maximum can reduce lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Available"
javaExecutableTitle = "Java Executable"
javaExecSelDialogTitle = "Select Java Executable"
javaExecSelButtonText = "Select File"
javaExecDesc = "The Java executable is verified before launching the game."
javaPathDesc = "The path must end with <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Additional JVM Options"
jvmOptsDesc = "Parameters provided to the JVM on execution. Do not include <em>-Xms</em> and <em>-Xmx</em>."
launcherTabHeaderText = "Launcher Settings"
launcherTabHeaderDesc = "Parameters related to the launcher."
allowPrereleaseTitle = "Allow pre-release updates."
allowPrereleaseDesc = "Pre-release versions include new features that may not be fully tested or integrated.<br>This will always be true if you are using a pre-release version."
dataDirectoryTitle = "Data Directory"
selectDataDirectory = "Select Data Directory"
chooseFolder = "Choose Folder"
dataDirectoryDesc = "All game files and local Java installations will be stored in the data directory.<br>Screenshots and saved worlds are stored in the server configuration folder."
aboutTabHeaderText = "About"
aboutTabHeaderDesc = "View information and release notes for the current version."
aboutTitle = "{appName}"
stableRelease = "Stable Release"
versionText = "Version "
sourceGithub = "Source Code (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Release Notes"
changelog = "Changelog"
noReleaseNotes = "No Release Notes"
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "Launcher Updates"
launcherUpdatesHeaderDesc = "Download, install, and check for launcher updates."
checkForUpdates = "Check for Updates"
whatsNew = "What's New"
updateReleaseNotes = "Update Release Notes"

[ejs.waiting]
waitingText = "Waiting for Microsoft.."

[ejs.welcome]
continueButton = "CONTINUE"

[js.discord]
waiting = "Waiting for client.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login]
login = "LOGIN"
loggingIn = "LOGGING IN..."
success = "SUCCESS"
tryAgain = "Try Again"

[js.login.error]
invalidValue = "* Invalid value"
requiredValue = "* Required field"

[js.login.error.unknown]
title = "Unknown Error on Login"
desc = "An unknown error occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "Please wait.."
failureTitle = "Error on Launch"
failureText = "See the console (CTRL + Shift + i) for details."
okay = "Continue"
serverUnavailableTitle = "Servers Unavailable"
serverUnavailableDesc = "Servers are unavailable, we will try to launch the downloaded version. If it doesn't launch, check your internet connection and restart the application."
serverUnavailableOkay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "No account selected"

[js.landing.selectedServer]
noSelection = "No server selected"
loading = "Loading.."

[js.landing.serverStatus]
server = "SERVER"
offline = "OFFLINE"
players = "PLAYERS"

[js.landing.systemScan]
checking = "Checking system information.."
noCompatibleJava = "No compatible<br>Java installation found"
installJavaMessage = "A 64-bit version of Java {major} is required to run Minecraft. Would you like to install it?"
installJava = "Install Java"
installJavaManually = "Install Manually"
javaDownloadPrepare = "Preparing Java download.."
javaDownloadFailureTitle = "Error Downloading Java"
javaDownloadFailureText = "See the console (CTRL + Shift + i) for details."
javaRequired = "Java Required<br>to Launch"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>See the <a href="https://envel-experimental.github.io/Site/java.html">Java Installation Guide</a> for instructions on installing Java.'
javaRequiredDismiss = "Understood"
javaRequiredCancel = "Go Back"

[js.landing.downloadJava]
findJdkFailure = "Could not find a distribution for OpenJDK."
javaDownloadCorruptedError = "The downloaded JDK distribution has an invalid hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Fatal Error"
unableToLoadDistributionIndex = "Could not load files from our servers. Try again or check your internet connection."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "Try again. See the console (CTRL + Shift + i) for details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Preparing to launch.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, could not be downloaded correctly. As a result, the game cannot launch.<br><br>To fix this, temporarily disable your antivirus software and relaunch the game.<br><br>If you have time, please <a href=\"https://github.com/Envel-Experimental/HeliosLauncher/issues\">report this</a> and specify which antivirus you use. We will contact them and try to resolve the issue."
doneEnjoyServer = "Done. Launching..."
checkConsoleForDetails = "Please see the console (CTRL + Shift + i) for details."
launchingOffline = "Launching offline copy. Server error."

[js.landing.news]
checking = "Checking for news"

[js.landing.discord]
loading = "Loading the game.."
joining = "Sailing to Westeros!"
joined = "Exploring the kingdom!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Something went wrong"
errorMessage = "Microsoft authentication error. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something went wrong"
errorMessage = "Error logging out of Microsoft account. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Select Account"
selectedButton = "Account Selected &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Warning<br>This is your last account"
lastAccountWarningMessage = "You must be logged into at least one account to use the launcher. You will need to log in again after logging out.<br><br>Are you sure you want to log out?"
confirmButton = "Confirm"
cancelButton = "Cancel"

[js.settings.authAccountPopulate]
username = "Username"
uuid = "UUID"
selectAccount = "Select Account"
selectedAccount = "Account Selected âœ“"
logout = "Logout"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Error Deleting<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Error Toggling<br>One or More Drop-in Mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Main Server"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Invalid Selection"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "New Release Available"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Downloading.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "You are using the latest version"
checkForUpdatesButton = "Check for Updates"
checkingForUpdatesButton = "Checking for updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Error"
errorMessage = "Could not authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Critical Error: Servers Unavailable"
fatalErrorMessage = "Could not connect to our servers.<br><br>Make sure you have an internet connection and restart the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "Failed to refresh login for <strong>{account}</strong>. Please select another account or log in again."
failedMessageSelectAnotherAccount = "Failed to refresh login for <strong>{account}</strong>. Please log in again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Checking for updates..."
installNowButton = "Install Now"
checkForUpdatesButton = "Check for Updates"

[js.auth.microsoft.error]
noProfileTitle = "Login Error:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account is not yet set up for Minecraft. If you recently purchased the game or received it through Xbox Game Pass, set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can do so on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Login Error:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account does not have an Xbox account linked."
xblBannedTitle = "Login Error:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is unavailable or blocked."
under18Title = "Login Error:<br>Parental Permission Required"
under18Desc = "Accounts for users under 18 must be added to a 'Family Group' by an adult."
unknownTitle = "Unknown Login Error"
unknownDesc = "An unknown error occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "Authentication endpoint not found. Please report this issue."
accountMigratedTitle = "Login Error:<br>Account Migrated"
accountMigratedDesc = "You tried to log in with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Login Error:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you entered is incorrect. Please try again."
tooManyAttemptsTitle = "Login Error:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts for this account recently. Please try again later."
invalidTokenTitle = "Login Error:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Login Error:<br>Token Already Has Profile"
tokenHasProfileDesc = "The access token is already linked to a profile. Profile selection is not yet implemented."
credentialsMissingTitle = "Login Error:<br>Missing Credentials"
credentialsMissingDesc = "Username/password not provided or password is less than 3 characters."
invalidSaltVersionTitle = "Login Error:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Login Error:<br>Account Migrated"
accountGoneDesc = "The account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Login Error:<br>Server Unavailable"
unreachableDesc = "Could not connect to the authentication servers. Make sure they are running and you have an internet connection."
gameNotPurchasedTitle = "Login Error:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to log in with does not have a purchased copy of Minecraft. You can buy it on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Login Error"
unknownErrorDesc = "An unknown error occurred. Please see the console for details."


[js.processbuilder.exit]
exitErrorHeader = "GAME ERROR. IF IT PERSISTS, CONTACT SUPPORT."
message = "The game exited with error code: "

[js.processbuilder.exit.crash]
title = "Oops, something went wrong"
body = "An error occurred with code {exitCode}.<br><br>Try disabling your antivirus and restarting the program as an administrator. If that doesn't help, contact support.<br><br>Sometimes disabling optimizations helps."
close = "Close"
disable = "Disable Optimizations"

[js.processbuilder.exit.disabled]
title = "Optimizations Disabled"
body = "We have disabled optimizations. You can always revert the modifications in the settings. Try launching the game again."
close = "Close"

[js.processbuilder.crash]
title = "Crash Analysis"
body = "A potential issue was detected: {description}"
close = "Close"
fix = "Fix ({fileName})"

[js.systemChecks]
warningTitle = "Technical Issues"
lowTotalRAM = "Your computer has less than 6 GB of RAM. We cannot guarantee the launcher will work on this computer, as it is weaker than the minimum technical requirements."
lowFreeRAM = "It seems your computer has very little free RAM. Try closing all unnecessary programs. We cannot guarantee the game will work stably."
lowDiskSpace = "It seems you have very little space on your main drive and the game may not install as it will not have enough memory. You need to clean your main drive."

[js.uicore.update]
updateAvailableTitle = "Update Available"
updateAvailableDesc = "A new update is available. Install now?"
updateButton = "Update"
updateFromSiteButton = "Update from Site"
laterButton = "Later"
